{
 "title": "NEAR / Validators",
 "description": "NEAR Validators Performance Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(near_build_info, namespace)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(near_build_info{namespace=\"$namespace\"}, pod)"
    }
   },
   {
    "name": "account_id",
    "label": "AccountID",
    "query": {
     "query": "label_values(near_validator_account{namespace=\"$namespace\", pod=\"$pod\"}, account_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "near_build_info{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{build}}"
    }
   ]
  },
  {
   "title": "Protocol Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "near_node_protocol_version{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "near_node_db_version{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "near_validator_account{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{chain_id}}"
    }
   ]
  },
  {
   "title": "Network Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Block Height Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "near_block_height_head{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Final Block Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "near_final_block_height{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Header Height Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "near_header_head_height{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Epoch Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "near_epoch_height{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per Minute",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "near_blocks_per_minute{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Active Staked Validators",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(near_validator_active_total{namespace=\"$namespace\", job=\"$job\", pod=\"$pod\"})"
    }
   ]
  },
  {
   "title": "Peer Connected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "near_peer_connections_total{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Reachable",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "near_peer_reachable{namespace=\"$namespace\", pod=\"$pod\"}"
    }
   ]
  },
  {
   "title": "Actions Processed",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "near_action_called_count{namespace=\"$namespace\", pod=\"$pod\"}",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Blocks Produced in Network",
   "type": "timeseries",
   "description": "The number of blocks produced by this node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_blocks_produced{namespace=\"$namespace\", pod=\"$pod\", account_id=\"$account_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks Expected by Network",
   "type": "timeseries",
   "description": "The number of blocks expected by the network.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_blocks_expected{namespace=\"$namespace\", pod=\"$pod\", account_id=\"$account_id\"}",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  {
   "title": "Chunk Produced in Network",
   "type": "timeseries",
   "description": "The number of chunks produced by this node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_chunks_produced{namespace=\"$namespace\", pod=\"$pod\", account_id=\"$account_id\"}",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  {
   "title": "Chunkd Expected by Network",
   "type": "timeseries",
   "description": "The number of chunks expected by this network.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "near_validators_chunks_expected{namespace=\"$namespace\", pod=\"$pod\", account_id=\"$account_id\"}",
     "legendFormat": "{{account_id}}"
    }
   ]
  },
  {
   "title": "Node Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {}
   ]
  }
 ]
}